/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarenkorbRouteImport } from './routes/warenkorb'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as KasseRouteImport } from './routes/kasse'
import { Route as BestellungBestaetigtRouteImport } from './routes/bestellung-bestaetigt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'

const WarenkorbRoute = WarenkorbRouteImport.update({
  id: '/warenkorb',
  path: '/warenkorb',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const KasseRoute = KasseRouteImport.update({
  id: '/kasse',
  path: '/kasse',
  getParentRoute: () => rootRouteImport,
} as any)
const BestellungBestaetigtRoute = BestellungBestaetigtRouteImport.update({
  id: '/bestellung-bestaetigt',
  path: '/bestellung-bestaetigt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bestellung-bestaetigt': typeof BestellungBestaetigtRoute
  '/kasse': typeof KasseRoute
  '/shop': typeof ShopRouteWithChildren
  '/warenkorb': typeof WarenkorbRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bestellung-bestaetigt': typeof BestellungBestaetigtRoute
  '/kasse': typeof KasseRoute
  '/shop': typeof ShopRouteWithChildren
  '/warenkorb': typeof WarenkorbRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bestellung-bestaetigt': typeof BestellungBestaetigtRoute
  '/kasse': typeof KasseRoute
  '/shop': typeof ShopRouteWithChildren
  '/warenkorb': typeof WarenkorbRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bestellung-bestaetigt'
    | '/kasse'
    | '/shop'
    | '/warenkorb'
    | '/shop/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bestellung-bestaetigt'
    | '/kasse'
    | '/shop'
    | '/warenkorb'
    | '/shop/$slug'
  id:
    | '__root__'
    | '/'
    | '/bestellung-bestaetigt'
    | '/kasse'
    | '/shop'
    | '/warenkorb'
    | '/shop/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BestellungBestaetigtRoute: typeof BestellungBestaetigtRoute
  KasseRoute: typeof KasseRoute
  ShopRoute: typeof ShopRouteWithChildren
  WarenkorbRoute: typeof WarenkorbRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warenkorb': {
      id: '/warenkorb'
      path: '/warenkorb'
      fullPath: '/warenkorb'
      preLoaderRoute: typeof WarenkorbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasse': {
      id: '/kasse'
      path: '/kasse'
      fullPath: '/kasse'
      preLoaderRoute: typeof KasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestellung-bestaetigt': {
      id: '/bestellung-bestaetigt'
      path: '/bestellung-bestaetigt'
      fullPath: '/bestellung-bestaetigt'
      preLoaderRoute: typeof BestellungBestaetigtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BestellungBestaetigtRoute: BestellungBestaetigtRoute,
  KasseRoute: KasseRoute,
  ShopRoute: ShopRouteWithChildren,
  WarenkorbRoute: WarenkorbRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
