/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarenkorbRouteImport } from './routes/warenkorb'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KasseRouteImport } from './routes/kasse'
import { Route as BewertungenRouteImport } from './routes/bewertungen'
import { Route as BestellungBestaetigtRouteImport } from './routes/bestellung-bestaetigt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'

const WarenkorbRoute = WarenkorbRouteImport.update({
  id: '/warenkorb',
  path: '/warenkorb',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KasseRoute = KasseRouteImport.update({
  id: '/kasse',
  path: '/kasse',
  getParentRoute: () => rootRouteImport,
} as any)
const BewertungenRoute = BewertungenRouteImport.update({
  id: '/bewertungen',
  path: '/bewertungen',
  getParentRoute: () => rootRouteImport,
} as any)
const BestellungBestaetigtRoute = BestellungBestaetigtRouteImport.update({
  id: '/bestellung-bestaetigt',
  path: '/bestellung-bestaetigt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bestellung-bestaetigt': typeof BestellungBestaetigtRoute
  '/bewertungen': typeof BewertungenRoute
  '/kasse': typeof KasseRoute
  '/kontakt': typeof KontaktRoute
  '/shop': typeof ShopRouteWithChildren
  '/ueber-uns': typeof UeberUnsRoute
  '/warenkorb': typeof WarenkorbRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bestellung-bestaetigt': typeof BestellungBestaetigtRoute
  '/bewertungen': typeof BewertungenRoute
  '/kasse': typeof KasseRoute
  '/kontakt': typeof KontaktRoute
  '/shop': typeof ShopRouteWithChildren
  '/ueber-uns': typeof UeberUnsRoute
  '/warenkorb': typeof WarenkorbRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bestellung-bestaetigt': typeof BestellungBestaetigtRoute
  '/bewertungen': typeof BewertungenRoute
  '/kasse': typeof KasseRoute
  '/kontakt': typeof KontaktRoute
  '/shop': typeof ShopRouteWithChildren
  '/ueber-uns': typeof UeberUnsRoute
  '/warenkorb': typeof WarenkorbRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bestellung-bestaetigt'
    | '/bewertungen'
    | '/kasse'
    | '/kontakt'
    | '/shop'
    | '/ueber-uns'
    | '/warenkorb'
    | '/shop/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bestellung-bestaetigt'
    | '/bewertungen'
    | '/kasse'
    | '/kontakt'
    | '/shop'
    | '/ueber-uns'
    | '/warenkorb'
    | '/shop/$slug'
  id:
    | '__root__'
    | '/'
    | '/bestellung-bestaetigt'
    | '/bewertungen'
    | '/kasse'
    | '/kontakt'
    | '/shop'
    | '/ueber-uns'
    | '/warenkorb'
    | '/shop/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BestellungBestaetigtRoute: typeof BestellungBestaetigtRoute
  BewertungenRoute: typeof BewertungenRoute
  KasseRoute: typeof KasseRoute
  KontaktRoute: typeof KontaktRoute
  ShopRoute: typeof ShopRouteWithChildren
  UeberUnsRoute: typeof UeberUnsRoute
  WarenkorbRoute: typeof WarenkorbRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warenkorb': {
      id: '/warenkorb'
      path: '/warenkorb'
      fullPath: '/warenkorb'
      preLoaderRoute: typeof WarenkorbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasse': {
      id: '/kasse'
      path: '/kasse'
      fullPath: '/kasse'
      preLoaderRoute: typeof KasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bewertungen': {
      id: '/bewertungen'
      path: '/bewertungen'
      fullPath: '/bewertungen'
      preLoaderRoute: typeof BewertungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestellung-bestaetigt': {
      id: '/bestellung-bestaetigt'
      path: '/bestellung-bestaetigt'
      fullPath: '/bestellung-bestaetigt'
      preLoaderRoute: typeof BestellungBestaetigtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BestellungBestaetigtRoute: BestellungBestaetigtRoute,
  BewertungenRoute: BewertungenRoute,
  KasseRoute: KasseRoute,
  KontaktRoute: KontaktRoute,
  ShopRoute: ShopRouteWithChildren,
  UeberUnsRoute: UeberUnsRoute,
  WarenkorbRoute: WarenkorbRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
